'use strict';
require('dotenv').config();
const express = require('express');
const path = require('node:path');
const app = express();
app.disable('x-powered-by');
app.use(express.json({ limit: '8kb' }));
app.all('/api/owner-session', require('./api/owner-session'));
app.all('/api/scan', require('./api/scan'));
app.get('/api/health', (_req, res) => res.json({ ok: true, service: 'AskVeyza' }));
app.use('/assets', express.static(path.join(__dirname, 'assets')));
app.get(['/owner', '/owner.html', '/scanner-report', '/scanner-report.html', '/weekly-report', '/weekly-report.html'], (_req, res) => {
  res.set({ 'Cache-Control': 'no-store', 'X-Robots-Tag': 'noindex, nofollow' });
  res.sendFile(path.join(__dirname, 'owner.html'));
});
const redirects = { pricing: '/#pricing', 'how-it-works': '/#how', demo: '/#demo-video', waitlist: '/#request' };
for (const [from, to] of Object.entries(redirects)) app.get(['/' + from, '/' + from + '.html'], (_req, res) => res.redirect(302, to));
app.get(['/', '/index.html'], (req, res) => res.sendFile(path.join(__dirname, req.hostname === 'askveyza-owner.vercel.app' ? 'owner.html' : 'index.html')));
for (const file of ['robots.txt', 'sitemap.xml', 'success.html', 'cancel.html']) app.get('/' + file, (_req, res) => res.sendFile(path.join(__dirname, file)));
app.use((_req, res) => res.status(404).send('Page not found'));
if (require.main === module) app.listen(process.env.PORT || 5500, () => console.log('AskVeyza is ready.'));
module.exports = app;
